amal/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("polls.urls")),
    path("admin/", admin.site.urls),
    path('', include('django_dyn_dt.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = "amal"

urlpatterns = [
    path("", views.loginpage, name="loginpage"),
    path("loginUser", views.loginUser, name="loginUser"),
    path("showtable", views.showtable, name="showtable"),
]

polls/models.py
from django.db import models

class listamal(models.Model):
    Choicesolaviat = (
        ('اورژانسی','اورژانسی'),
        ('پرخطر','پرخطر'),
        ('آسیب پذیر','آسیب پذیر'),
        ('عفونی','عفونی'),
        ('الکتیو','الکتیو'),
    )
    Bimar = models.CharField(max_length=300, null=True, blank=True)
    Age = models.CharField(max_length=300, null=True, blank=True)
    Doctor = models.CharField(max_length=300, null=True, blank=True)
    ProfBihooshi = models.CharField(max_length=300, null=True, blank=True)
    Typeamal = models.CharField(max_length=300, null=True, blank=True)
    Otagh = models.CharField(max_length=300, null=True, blank=True)
    Scrub = models.CharField(max_length=300, null=True, blank=True)
    Circuler = models.CharField(max_length=300, null=True, blank=True)
    KarshenasBihooshi = models.CharField(max_length=300, null=True, blank=True)
    KarshenasOtasghamal = models.CharField(max_length=300, null=True, blank=True)
    Time = models.CharField(max_length=300, null=True, blank=True)
    Olaviat = models.CharField(max_length=300, choices= Choicesolaviat, null=True, blank=True)
    Status = models.CharField(max_length=300, null=True, blank=True)

polls/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.shortcuts import redirect
# from users.models import User
from .models import listamal
from django.http import JsonResponse
from django.core import serializers
import json
# from django_dyn_dt.datatb import DataTB
from django.urls import reverse
from django.http import HttpResponseRedirect




def showtable(request):
    pass
    # # user = User.objects.filter(id = id)
    # list = listamal.objects.all()
    # # return HttpResponse(list[0])
    # return render(requset, "showtable.html",{
    #     'lists' : list ,
    # })
    # context = {}
    # # ddt = DataTB(model_class_path="polls.models.listamal")
    # # context['data_table1'] = ddt.render()
    # return render(request, 'showtable.html', context=context)



def loginpage(request):
    return render(request, 'loginpage.html')



def loginUser(request):
    Username = request.POST.get('username')
    Password = request.POST.get('password')
    user = authenticate(request, username=Username, password=Password)
    if user is not None:
        # return HttpResponse(user.Hospital)
        login(request, user)
        return redirect("datatb/listamal")
    else:
        return HttpResponse("Fails")

templates/addlist.html
<style>
/* all */
@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap");

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: "Poppins", sans-serif;
}

:root {
  --main-blue: #71b7e6;
  --main-purple: #9b59b6;
  --main-grey: #ccc;
  --sub-grey: #d9d9d9;
}

body {
  display: flex;
  height: 100vh;
  justify-content: center; /*center vertically */
  align-items: center; /* center horizontally */
  background: linear-gradient(135deg, var(--main-blue), var(--main-purple));
  padding: 10px;
}
/* container and form */
.container {
  max-width: 1000px;
  width: 100%;
  background: #fff;
  padding: 25px 30px;
  border-radius: 5px;
}
.container .title {
  font-size: 25px;
  font-weight: 500;
  position: relative;
}



.container form .user__details {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  margin: 20px 0 12px 0;
}
/* inside the form user details */
form .user__details .input__box {
  width: 300px;
  margin-bottom: 15px;
}

.user__details .input__box .details {
  font-weight: 500;
  margin-bottom: 5px;
  display: block;
}
.user__details .input__box input {
  height: 45px;
  width: 100%;
  outline: none;
  border-radius: 5px;
  border: 1px solid var(--main-grey);
  padding-left: 15px;
  font-size: 16px;
  border-bottom-width: 2px;
  transition: all 0.3s ease;
}

.user__details .input__box input:focus,
.user__details .input__box input:valid {
  border-color: var(--main-purple);
}


form input[type="radio"] {
  display: none;
}

/* submit button */
form .button {
  height: 45px;
  margin: 45px 0;
}

form .button input {
  height: 100%;
  width: 100%;
  outline: none;
  color: #fff;
  border: none;
  font-size: 18px;
  font-weight: 500;
  border-radius: 5px;
  background: linear-gradient(135deg, var(--main-blue), var(--main-purple));
  transition: all 0.3s ease;
}

form .gender__details .gender__title {
  font-size: 20px;
  font-weight: 500;
}

form .gender__details .category {
  display: flex;
  width: 100%;
  margin: 15px 0;
  justify-content: space-between;
}

.gender__details .category label {
  display: flex;
  align-items: center;
}

.gender__details .category .dot {
  height: 18px;
  width: 18px;
  background: var(--sub-grey);
  border-radius: 50%;
  margin: 10px;
  border: 5px solid transparent;
  transition: all 0.3s ease;
}

#dot-1:checked ~ .category .one,
#dot-2:checked ~ .category .two,
#dot-3:checked ~ .category .three,
#dot-4:checked ~ .category .four,
#dot-5:checked ~ .category .five {
  border-color: var(--sub-grey);
  background: var(--main-purple);
}

form .button input:hover {
  background: linear-gradient(-135deg, var(--main-blue), var(--main-purple));
}


</style>

<div class="container">
  <div class="title">اضافه کردن بیمار</div>
  <form action="#">
    <div class="user__details">
      <div class="input__box">
        <span class="details">نام بیمار</span>
        <input type="text" placeholder="" required>
      </div>
      <div class="input__box">
        <span class="details">سن بیمار</span>
        <input type="text" placeholder="" required>
      </div>
      <div class="input__box">
        <span class="details">پزشک جراح</span>
        <input type="text" placeholder="" required>
      </div>
      <div class="input__box">
        <span class="details">متخصص بیهوشی</span>
        <input type="text" placeholder="" required>
      </div>
      <div class="input__box">
        <span class="details">نوع عمل</span>
        <input type="text" placeholder="" required>
      </div>
      <div class="input__box">
        <span class="details">اتاق</span>
        <input type="text" placeholder="" required>
      </div>
      <div class="input__box">
        <span class="details">اسکراب</span>
        <input type="text" placeholder="" required>
      </div>
      <div class="input__box">
        <span class="details">سیرکولر</span>
        <input type="text" placeholder="" required>
      </div>
      <div class="input__box">
        <span class="details">کارشناس بیهوشی</span>
        <input type="text" placeholder="" required>
      </div>
      <div class="input__box">
        <span class="details">کارشناس اتاق عمل</span>
        <input type="text" placeholder="" required>
      </div>
      <div class="input__box">
        <span class="details">ساعت</span>
        <input type="text" placeholder="" required>
      </div>
      <div class="input__box">
        <span class="details">وضعیت</span>
        <input type="text" placeholder="" required>
      </div>
      <div class="gender__details">
      <input type="radio" name="gender" id="dot-1">
      <input type="radio" name="gender" id="dot-2">
      <input type="radio" name="gender" id="dot-3">
      <input type="radio" name="gender" id="dot-4">
      <input type="radio" name="gender" id="dot-5">
      <span class="gender__title">اولویت بندی</span>
      <div class="category">
        <label for="dot-1">
          <span class="dot one"></span>
          <span>اورژانسی</span>
        </label>
        <label for="dot-2">
          <span class="dot two"></span>
          <span>پرخطر</span>
        </label>
        <label for="dot-3">
          <span class="dot three"></span>
          <span>آسیب پذیر</span>
        </label>
        <label for="dot-4">
          <span class="dot four"></span>
          <span>عفونی</span>
        </label>
        <label for="dot-5">
          <span class="dot five"></span>
          <span>الکتیو</span>
        </label>
      </div>
    </div>

    </div>
    <div class="button">
      <input type="submit" value="اضافه کردن">
    </div>
  </form>
</div>

templates/index.html
{% load static %}


<style>
#dropdownMenuButton1{
    display: none;
}

.dataTable-bottom{
    display: none;
}

.dataTable-sorter{
    display: none;
}

#export-container{
    display: none;
}




.orj{
    background-color: red !important;
}

.asib{
    background-color: yellow !important;
}

.por{
    background-color: orange !important;
}

.ofoni{
    background-color: blue !important;
}

.elective{
    background-color: white !important;
}

.sjd{
    background-color: red;
}


#ida{
    display: none;
}
</style>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- data-tables -->
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" type="text/css">
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@3.2.0"               type="text/javascript"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <!-- bootstrap5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">

    <link rel="stylesheet" href="{% static 'src/style/myStyle.css' %}">

</head>
<body>



    <datalist id="sjd1221">
        <option value="اورژانسی">اورژانسی</option>
        <option value="پر خطر">پر خطر</option>
        <option value="آسیب پذیر">آسیب پذیر</option>
        <option value="عفونی">عفونی</option>
        <option value="الکتیو">الکتیو</option>
    </datalist>
    <datalist id="sss">
        <option value="پذیرش">پذیرش</option>
        <option value="داخل اتاق">داخل اتاق</option>
        <option value="ریکاوری">ریکاوری</option>
        <option value="انتقال به بخش">انتقال به بخش</option>
    </datalist>


    <div class="d-flex flex-column mx-5">

        <!-- page title -->

        <div class="p-3 rounded bg-light item">
            <table id="sjd" class="table"></table>
        </div>


        <div class="dataTable-top d-flex justify-content-between">
            <h1 class="model-name"></h1>
            <button id="stop" style="background-color: green; ">فعال</button>
        </div>

        <!-- DATA Container -->
        

    </div>
  
    <!--Pagination-->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {% if has_prev %}
            <li class="page-item">
            <a class="page-link" href="?page={{ current_page|add:"-1" }}&entries={{ entries }}&search={{ search }}"> &laquo; </a>
          </li>
        {% else %}
            <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="True"> &laquo; </a>
          </li>
        {% endif %}

        {% if current_page|add:'-4' > 1 %}
            <li class="page-item"><a class="page-link" >&hellip;</a></li>
        {% endif %}

        {% for i in total_pages %}
            {% if current_page == i %}
                <li class="page-item active" aria-current="page">
                <span class="page-link">
                    {{ i }}
              </span>
            </li>
            {% else  %}
                 <li class="page-item"><a class="page-link" href="?page={{ i }}&entries={{ entries }}&search={{ search }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if total_pages|length > current_page|add:'4' %}
           <li class="page-item"><a class="page-link" >&hellip;</a></li>
        {% endif %}

        {% if has_next %}
            <li class="page-item">
            <a class="page-link" href="?page={{ current_page|add:"1" }}&entries={{ entries }}&search={{ search }}"> &raquo; </a>
          </li>
        {% else %}
            <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="True"> &raquo; </a>
          </li>
        {% endif %}
      </ul>
    </nav>

    <!-- Edit/Create Modal -->
    <div class="modal fade" 
         id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>

          <form>{% csrf_token %}

          <div class="modal-body" id="form">
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <input type="submit" class="btn btn-primary modal-btn"/>
          </div>
        </form>


            <div class="alert alert-danger m-3 mt-0 d-none" role="alert">
            </div>
        </div>
      </div>
    </div>

    <!-- Notification Toast -->
    <div class="toast-container position-fixed bottom-0 start-0 p-3 " >
      <div id="liveToast" class="toast text-light bg-primary" data-bs-autohide="false" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
          <div class="toast-body">
            Hello! This is a sample toast.
          </div>
          <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      </div>
    </div>




    <script type="module">


      import {setData , setModelName} from "{% static 'data/index.js' %}"
      const title = ["نام", "سن"]

      const headings = [
        {% for item in headings %}
          '{{ item }}',
        {% endfor %}
      ];

      const data = [
        {% for item in data %}
            [{% for i in item %}
                '{{ i }}',
            {% endfor %}],
        {% endfor %}
      ];

      const isDate = [
          {% for item in is_date %}
              '{{ item }}',
          {% endfor %}
      ];

      setData(headings , data , isDate);

      setModelName(
          '{{ model_name }}'
      );


    </script>

    <script type="module" src="{% static 'src/index.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function(){
            var headingHead = {
                'id' : 'ردیف'  ,
                'Bimar' : 'بیمار',
                'Age' : 'سن' ,
                'Doctor' : 'دکتر' ,
                'ProfBihooshi' : 'متخصص بیهوشی' ,
                'Typeamal' : 'نوع عمل' ,
                'Otagh' : 'اتاق' ,
                'Scrub' : 'اسکراب' ,
                'Circuler' : 'سیرکولر' ,
                'KarshenasBihooshi' : 'کارشناس بیهوشی' ,
                'KarshenasOtasghamal' : 'کارشناس اتاق عمل' ,
                'Time' : 'ساعت' ,
                'Olaviat' : 'اولویت' ,
                'Status' : 'وضعیت' ,

            };
            var items = $(".dataTable-sorter").toArray();
            for(let i = 0 ; i < items.length ; i++ ){
                    $(items[i]).text(headingHead[items[i].innerText]);
            };
            $("tr.alt:even").addClass("even");
            $("tr.alt:odd").addClass("odd");
            var z = $("tr");
            for(let j = 0 ; j < z.length; j++ ){
                if(z[j].rowIndex % 2 == 1){
                    $("tr:odd").css("background-color", "#dee2e6");
                };
                if(z[j].rowIndex % 2 == 0){
                    $("tr:even").css("background-color", "#ffffff");
                };
            };
            var inter = setInterval(function(){
                if({{current_page}} != {{total_pages|length}}){
                    location.replace("?page={{ current_page|add:"1" }}#sjd")
                }
                else{
                    location.replace("?page= 1#sjd ")
                }
            }, 20000);        
            $("#stop").click(function(){
            if ($("#stop").text() == "فعال"){
                $("#stop").css("background-color", "darkred");
                $("#stop").css("color", "white");
                $("#stop").text("غیر فعال");
                clearInterval(inter);
            }
            else{
                $("#stop").css("background-color", "green");
                $("#stop").css("color", "black");
                $("#stop").text("فعال");
                setInterval(function(){
                if({{current_page}} != {{total_pages|length}}){
                    location.replace("?page={{ current_page|add:"1" }}#sjd")
                }
                else{
                    location.replace("?page= 1 ")
                }
            }, 20000); 
            }
            });

            });
    </script>
  
</body>
</html>

templates/loginpage.html
<style>
{% load static %}
@import url("https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap");

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  outline: none;
  transition: 0.6s;
}

body {
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  height: 100vh;
  font-family: "Ubuntu", sans-serif;
}

.input {
  position: relative;
}

.input label {
  position: absolute;
  color: #5c616c;
  font-size: 0.8rem;
  pointer-events: none;
  top: 9px;
  left: 7px;
}

.input input {
  border: none;
  box-shadow: 0 2px 2px #0000001c;
  height: 32px;
  margin-bottom: 8px;
  border-radius: 5px;
  padding: 0 7px;
  font-size: 0.9rem;
  width: 191px;
}

.submit {
  padding: 4px 1px;
  width: 69px;
  height: 27px;
  font-size: 0.9rem;
  border: none;
  border-radius: 5px;
}

.login {
  background-color: #2777ff;
  color: #ffffff;
}


.button-event {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 22px;
  height: 67px;
}

.box-entry {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 22px;
  box-shadow: 0 1px 4px #0000002b;
  background-color: #eaf6f9;
  height: 110px;
  padding-top: 22px;
}

.profile {
  width: 75px;
  height: auto;
  margin-left: 11px;
}

.main-container {
  width: 333px;
  height: fit-content;
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  margin: auto;
  background-color: #ffffff;
  border-radius: 5px;
  border-bottom: 4px solid #cccccc;
  overflow: hidden;
}

.username {
  color: #5c616c;
  pointer-events: none;
}

.header-main {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background-color: #edf3f9;
  height: 29px;
  padding: 0 6px;
}

.input input:focus ~ label,
.input input:valid ~ label {
  display: none;
}


.show {
  display: block !important;
}

@media only screen and (max-width: 367px) {
  .main-container {
    width: 223px;
  }
  .box-entry {
    gap: 9px;
  }
  .profile {
    margin-left: 0;
  }
  .input input {
    width: 100%;
  }
  .input label {
    font-size: 0.6rem;
    top: 10px;
  }

}

</style>




<main class="main-container">
  <form class="login-form" action="{% url 'amal:loginUser' %}" method="post">
  {% csrf_token %}
  <div class="box-entry">
    <div>
      <img src="https://aqdasiyeh.nikan.hospital/wp-content/uploads/sites/6/2022/12/logo-png.png" alt="kali" class="profile" />
    </div>
    <div class="input-main">
      <input type="hidden" name="id" value="{{ user.id }}">
      <input name="username" autocomplete="off" type="username" placeholder="USERNAME">
      <input name="password" autocomplete="off" type="password" placeholder="PASSWORD">
    </div>
  </div>
  <div class="button">
    <button class="submit" id="login">Log In</button>
  </div>
  </form>
</main>

templates/showtable.html
<body>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.5/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.4.0/css/buttons.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/datetime/1.5.0/css/dataTables.dateTime.min.css">
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.0/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/datetime/1.5.0/js/dataTables.dateTime.min.js"></script>
<script src="https://editor.datatables.net/extensions/Editor/js/dataTables.editor.min.js"></script>


<div class="container" style="margin-top:10px;">
<div class="row">
              <div class="col-sm-12 col-md-12">         
                {{ data_table1 }}
              </div>
            </div>


</body>


<style>
/*
    #example input, #example select {
  font-size:14px;
  padding:5px 5 5px 5px;
  display:block;
  width:100%;
  border:none;
  background: transparent;
  
}

#example input:focus,#example select:focus  { outline:none; border-bottom:1px solid #757575;}*/





</style>

<script>


$(document).ready(function() {
    $('#example').DataTable();
} );
function saveData(event,fieldname,primaryid){
            console.log($('#'+event.target.id).val());
            console.log(fieldname);
            console.log(primaryid);
        }

 </script>